version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    hostname: app
    image: testapp
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - dbdata:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    container_name: nginx
    expose:
      - 8080
    ports:
      - "80:8080"
    depends_on:
      - app
volumes:
  dbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./dbdata